# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

name: Auto-Clean

on:
  #自动清理：每天早上5点
  schedule:
    - cron: 0 21 * * *
  #手动清理
  workflow_dispatch:

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          #仓库仅发布N60 Pro固件；始终保留最近3个版本
          releases_keep_latest: 3
          delete_tags: true
